bot:
  name: MyFirstWeatherBot
  token: 658153349:AAGeJ2Ve88cQHo25M5gCMPBNjpQWaRdJUmg

proxy:
  host: 195.201.124.134
  port: 3128

weather:
  connectionTimeout: 5000
  readTimeout: 5000
  token: 6a185e4733913747ba365735273030a0
  url: http://api.openweathermap.org/data/2.5/

post:
  connectionTimeout: 5000
  readTimeout: 5000
  url: https://tracking.russianpost.ru/rtm34?wsdl
  login: UAqSeIyMRAdHeL
  password: 6mUOF9j9fT92